
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER IGNACIO IDENTIFIED BY "1234"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

ALTER USER IGNACIO QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO IGNACIO;

GRANT "RESOURCE" TO IGNACIO;

ALTER USER IGNACIO DEFAULT ROLE "RESOURCE";