CREATE TABLE TB_CATEGORIA(
    CODIGO_CA INT,
    DESCRIPCION_CA VARCHAR(30)
);

CREATE TABLE TB_MEDIDAS(
    CODIGO_ME NUMBER(3,0),
    ABREVIATURA_ME VARCHAR2(3),
    DESCRIPCION VARCHAR2(20)
);

CREATE TABLE TB_ARTICULOS(
    CODIGO_AR NUMBER(2,0),
    DESCRIPCION_AR VARCHAR2(50),
    MARCA_AR VARCHAR2(30),
    CODIGO_ME NUMBER(3,0),
    CODIGO_CA NUMBER(4,0),
    FECHA_ING DATE,
    STOCK_ACTUAL DECIMAL(10,2)
);

CREATE TABLE TB_ALMACENES(
    CODIGO_AL NUMBER(2,0) GENERATED ALWAYS AS IDENTITY,
    DESCRIPCION_AL VARCHAR(30)
);
--Eliminar tablas
DROP TABLE TB_CATEGORIA;

--Alterar campos
ALTER TABLE TB_CATEGORIA MODIFY(
    CODIGO_CA NOT NULL
);

ALTER TABLE TB_CATEGORIA MODIFY(
    DESCRIPCION_CA NOT NULL
);

ALTER TABLE TB_MEDIDAS MODIFY(
    CODIGO_ME NOT NULL
);
ALTER TABLE TB_ARTICULOS MODIFY(
    CODIGO_AR NOT NULL
);

ALTER TABLE TB_MEDIDAS MODIFY(
    DESCRIPCION VARCHAR(30)
);

ALTER TABLE TB_ARTICULOS DROP COLUMN MARCA_AR;

ALTER TABLE TB_ARTICULOS MODIFY CODIGO_AR NUMBER(6,0) DEFAULT 0;

ALTER TABLE TB_CATEGORIA MODIFY CODIGO_CA NUMBER (4,0) DEFAULT 0;

ALTER TABLE TB_MEDIDAS MODIFY CODIGO_ME NUMBER (3,0) DEFAULT 0;

ALTER TABLE TB_ARTICULOS ADD MARCAR_AR VARCHAR2(30);

ALTER TABLE TB_ARTICULOS DROP COLUMN STOCK_ACTUAL;

ALTER TABLE TB_ARTICULOS ADD PRIMARY KEY (CODIGO_AR);
ALTER TABLE TB_CATEGORIA ADD PRIMARY KEY (CODIGO_CA);
ALTER TABLE TB_MEDIDAS ADD PRIMARY KEY (CODIGO_ME);

ALTER TABLE TB_ARTICULOS 
ADD CONSTRAINT FK_01
FOREIGN KEY (CODIGO_ME) REFERENCES TB_MEDIDAS(CODIGO_ME);

ALTER TABLE TB_ARTICULOS
ADD CONSTRAINT FK_02
FOREIGN KEY (CODIGO_CA) REFERENCES TB_CATEGORIA (CODIGO_CA);







