
--Funciones numéricas

-- Redondea
SELECT ROUND(135.657,1) FROM DUAL;

--De esta manera los recorta pero no redondea
SELECT TRUNC (135.657,2) FROM DUAL;

--Devuelve el residuo
SELECT MOD(11,2) FROM DUAL;

SELECT COUNT(CODIGO_AR)AS TOTAL_REGISTROS FROM TB_ARTICULOS;

SELECT SUM(CODIGO_AR)AS SUMA_TOTAL FROM TB_ARTICULOS;

SELECT MIN(CODIGO_AR)FROM TB_ARTICULOS;

SELECT MAX (CODIGO_AR)FROM TB_ARTICULOS; 

SELECT AVG (CODIGO_AR) FROM TB_ARTICULOS;
