-- Funciones string
-- NOTA, LA TABLA DUAL, ya la trae ORACLE
SELECT CONCAT ('Hola Ignacio','Curso de Base de Datos Oracle Database') FROM DUAL;

SELECT CHR (65) FROM DUAL;

SELECT initcap('hola ignacio rueda') FROM DUAL;

SELECT upper('hola ignacio rueda') FROM DUAL;

SELECT lower ('HOLA IGNACIO RUEDA') FROM DUAL;

-- sintaxis : LPAD(EXPRESION_TEXTO,CANT_RELLENO,TEXTO_RELLENO) RELLENAR

SELECT LPAD('IGNACIO',12,'x')FROM DUAL;

SELECT CONCAT ('FAC-',LPAD('10',5,0)) FROM DUAL;

SELECT RPAD('IGNACIO',11,'x') FROM DUAL;

SELECT CONCAT (RPAD('P-',10,'0'),1) FROM DUAL;

--FUNCIONES LTRIM () RTRIM () -> LIMPIAR ESPACIOS EN BLANCO UNO A LEFT Y OTRO RIGHT
SELECT CONCAT(RTRIM('IGNACIO        '),'RUEDA') FROM DUAL;

--FUNCIONES REPLACE (EXPRESION_TEXT,CARACTER_BUSCADO,CARACTER_REEMPLAZO)

SELECT REPLACE ('IGNACIO','O','A') FROM DUAL;

-- FUNCIÓN SUBSTR (EXPRESION_TEXTO,POSICION_INICIAL,CANTIDAD_CARAC)

SELECT SUBSTR('IGNACIO',0,3) FROM DUAL;

SELECT LENGTH('IGNACIO') FROM DUAL;

-- INSTR (CADENA,SUBCADENA) -> Nos dice en qué posición se encuentra (la primera que encuentre)
SELECT INSTR('CURSO DE BASE DE DATOS','DE') FROM DUAL;

-- FUNCIONES TRANSLATE(EXPRESION_TEXTO,CONTENIDO_A_BUSCAR,CONTENIDO_DE_REEMPLAZO)

SELECT TRANSLATE('CURSO DE BASE DE DATOS','OES','035') FROM DUAL;



