-- FUNCIONES DE FECHA Y HORA

SELECT CURRENT_DATE FROM DUAL;


SELECT ADD_MONTHS (CURRENT_DATE,1)  FROM DUAL;


SELECT ADD_MONTHS ('01/12/2022',2) FROM DUAL;

SELECT LAST_DAY ('01/12/2022') FROM DUAL;

SELECT LAST_DAY ('01/02/2022') FROM DUAL;

SELECT MONTHS_BETWEEN ('01/05/2022','01/01/2022') FROM DUAL;
--Te dice cuándo será el próximo sábado
SELECT NEXT_DAY (CURRENT_DATE,'SÁBADO') FROM DUAL;

-- Devuelve la fecha actual
SELECT SYSDATE FROM DUAL;

-- Fecha y hora actual
SELECT CURRENT_TIMESTAMP FROM DUAL;

SELECT SYSTIMESTAMP FROM DUAL;

-- Extraer información de una fecha

SELECT EXTRACT (MONTH FROM CURRENT_DATE) FROM DUAL;

SELECT EXTRACT (DAY FROM CURRENT_DATE) FROM DUAL;


SELECT CONCAT ('FECHA ACTUAL: ',TO_CHAR(SYSDATE)) FROM DUAL;

SELECT TO_DATE('06/03/2025')+2 FROM DUAL;