--Funciones

CREATE OR REPLACE FUNCTION F_SUMAR(p01 number,p02 number)
RETURN NUMBER
    AS
    BEGIN
    RETURN (p01+p02);
    END;
    
CREATE OR REPLACE FUNCTION F_EVALUAR_EDAD (p01 number)
    RETURN VARCHAR2
AS
    V_RETORNO VARCHAR2(50);
BEGIN
    V_RETORNO:='';
    IF p01 < 18 THEN
        V_RETORNO:='ERES MENOR DE EDAD';
    ELSE
        V_RETORNO:='ERES UN ADULTO';
    END IF;
    RETURN (V_RETORNO);
END;
    