SELECT 
C.DESCRIPCION_CA,
COUNT(A.DESCRIPCION_AR) AS TOTAL_ARTICULOS
FROM TB_CATEGORIA C
INNER JOIN TB_ARTICULOS A 
ON C.CODIGO_CA = A.CODIGO_CA
GROUP BY(C.DESCRIPCION_CA)
;

SELECT MARCA_AR,
        COUNT(MARCA_AR) AS TOTAL_ARTICULOS
FROM TB_ARTICULOS
GROUP BY MARCA_AR;


SELECT CURSO,
    SUM(NOTA1) AS TOTAL_SUMA_NOTA1
FROM TB_NOTAS_ALUMNOS
GROUP BY CURSO;