-- INSERTAR DATOS
INSERT INTO TB_CATEGORIA (CODIGO_CA,DESCRIPCION_CA) 
VALUES(3,'EVENTOS');


INSERT INTO TB_MEDIDAS (CODIGO_ME,ABREVIATURA_ME,DESCRIPCION)
VALUES(4,'LTS','LITROS');

INSERT INTO TB_ARTICULOS (CODIGO_AR,DESCRIPCION_AR,CODIGO_ME,CODIGO_CA,MARCAR_AR)
VALUES(6,'ESCRITORIO',1,1,'STANDARD');

-- ACTUALIZAR DATOS
ALTER TABLE TB_ARTICULOS RENAME COLUMN MARCAR_AR to MARCA_AR; --Modifico el nombre de la columna
UPDATE TB_ARTICULOS SET MARCA_AR = 'CANON' WHERE CODIGO_AR = 2;

UPDATE TB_ARTICULOS SET MARCA_AR = 'SAMSUNG' WHERE CODIGO_AR IN (3,4);
--Agregar un * a todos las descripciones que tengan marca standard
UPDATE TB_ARTICULOS SET DESCRIPCION_AR = DESCRIPCION_AR || '*' WHERE MARCA_AR = 'STANDARD';

-- Eliminar información
DELETE FROM TB_ARTICULOS WHERE MARCA_AR = 'STANDARD';

DELETE FROM TB_MEDIDAS WHERE CODIGO_ME IN (3,4);

