
--INNER JOIN
SELECT AR.CODIGO_AR,
    AR.DESCRIPCION_AR,
    MED.DESCRIPCION,
    CAT.DESCRIPCION_CA,
    AR.MARCA_AR,AR.STOCK_ACTUAL,
    AR.FECHA_REGISTRO,AR.ACTIVO 
FROM TB_ARTICULOS AR 
INNER JOIN TB_MEDIDAS MED ON AR.CODIGO_ME = MED.CODIGO_ME
INNER JOIN TB_CATEGORIA CAT ON AR.CODIGO_CA = CAT.CODIGO_CA;


--LEFT JOIN
SELECT CAT.CODIGO_CA,
    CAT.DESCRIPCION_CA, 
    ART.CODIGO_AR,
    ART.DESCRIPCION_AR
FROM TB_CATEGORIA CAT 
LEFT JOIN TB_ARTICULOS ART 
ON ART.CODIGO_CA = CAT.CODIGO_CA;


--RIGHT JOIN
SELECT 
    ART.CODIGO_AR,
    ART.DESCRIPCION_AR,
    ART.MARCA_AR,
    MED.DESCRIPCION
FROM TB_ARTICULOS ART
RIGHT JOIN TB_MEDIDAS MED ON ART.CODIGO_ME = MED.CODIGO_ME;


SELECT * FROM TB_ARTICULOS
ORDER BY MARCA_AR DESC,DESCRIPCION_AR DESC;

SELECT * FROM TB_ARTICULOS
ORDER BY 5;--No es necesario poner el nombre de la columna, puedes poner la posición de la columna








