-- CONSULTAS
SELECT * FROM TB_ARTICULOS WHERE CODIGO_CA = 2;

SELECT CODIGO_AR,DESCRIPCION_AR,MARCA_AR FROM TB_ARTICULOS WHERE CODIGO_CA = 2;

SELECT * FROM TB_ARTICULOS WHERE MARCA_AR IN ('LENOVO','CANON');

SELECT * FROM TB_ARTICULOS WHERE NOT MARCA_AR IN ('LENOVO','CANON');

SELECT * FROM TB_ARTICULOS WHERE DESCRIPCION_AR LIKE 'R%';



--OPERADORES

CREATE TABLE TB_NOTAS_ALUMNOS (
    CODIGO_ALUMNO NUMBER(3,0),
    NOMBRE_ALUMNO VARCHAR2(50),
    CURSO VARCHAR(30),
    NOTA1 NUMBER(2,0),
    NOTA2 NUMBER(2,0),
    NOTA3 NUMBER(2,0),
    PROMEDIO NUMBER(5,2)
);

INSERT INTO TB_NOTAS_ALUMNOS 
VALUES(
    1,
    'CARLOS',
    'MATEMÁTICA',
    13,
    14,
    17,
    0
);
INSERT INTO TB_NOTAS_ALUMNOS VALUES(
    2,
    'MARÍA',
    'MATEMÁTICA',
    15,
    11,
    15,
    0
);

INSERT INTO TB_NOTAS_ALUMNOS VALUES(
    3,
    'CESAR',
    'MATEMÁTICA',
    16,
    13,
    10,
    0
);



-- operadores aritméticos
SELECT * FROM TB_NOTAS_ALUMNOS;

SELECT CODIGO_ALUMNO,NOMBRE_ALUMNO,(NOTA1+NOTA2+NOTA3) AS NOTAS FROM TB_NOTAS_ALUMNOS;

SELECT CODIGO_ALUMNO,NOMBRE_ALUMNO, ((NOTA1+NOTA2)-NOTA3) AS RESULTADOS,NOTA3 FROM TB_NOTAS_ALUMNOS;

SELECT CODIGO_ALUMNO,NOMBRE_ALUMNO, (NOTA1*NOTA2) AS MULTIPLICACION FROM TB_NOTAS_ALUMNOS;

SELECT CODIGO_ALUMNO,NOMBRE_ALUMNO, ROUND(((NOTA1+NOTA2+NOTA3)/3),2) AS PROMEDIO FROM TB_NOTAS_ALUMNOS;

-- operaciones relacionales

SELECT * FROM TB_NOTAS_ALUMNOS WHERE NOTA1 = 15;

SELECT * FROM TB_NOTAS_ALUMNOS WHERE NOTA1 <> 15;

SELECT * FROM TB_NOTAS_ALUMNOS WHERE NOTA1 > 15;

-- operador concatenación

SELECT (CODIGO_ALUMNO || ' - '||NOMBRE_ALUMNO) AS CODIGO_ALUMNO,CURSO FROM TB_NOTAS_ALUMNOS;

-- operadores lógicos

SELECT * FROM TB_NOTAS_ALUMNOS WHERE NOTA1 >= 13 AND NOTA2 >= 13;

SELECT * FROM TB_NOTAS_ALUMNOS WHERE NOT NOTA1>= 15;







