--CREACIÓN DE VISTAS.
CREATE OR REPLACE VIEW VISTA_ARTICULOS
AS (
SELECT 
    A.CODIGO_AR,
    A.DESCRIPCION_AR,
    A.MARCA_AR,
    C.DESCRIPCION_CA,
    M.DESCRIPCION,
    A.STOCK_ACTUAL,
    A.FECHA_REGISTRO,
    A.ACTIVO
FROM TB_ARTICULOS A
INNER JOIN TB_CATEGORIA C ON A.CODIGO_CA = C.CODIGO_CA
INNER JOIN TB_MEDIDAS M ON A.CODIGO_ME = M.CODIGO_ME);

SELECT * FROM VISTA_ARTICULOS;

